# If you come from bash you might have to change your $PATH.
# export PATH=$HOME/bin:/usr/local/bin:$PATH

# Path to your oh-my-zsh installation.
  export ZSH=~/.oh-my-zsh

#export TERM=xterm-256color
# Set name of the theme to load. Optionally, if you set this to "random"
# it'll load a random theme each time that oh-my-zsh is loaded.
# See https://github.com/robbyrussell/oh-my-zsh/wiki/Themes
ZSH_THEME="agnoster"

# Set list of themes to load
# Setting this variable when ZSH_THEME=random
# cause zsh load theme from this variable instead of
# looking in ~/.oh-my-zsh/themes/
# An empty array have no effect
# ZSH_THEME_RANDOM_CANDIDATES=( "robbyrussell" "agnoster" )

# Uncomment the following line to use case-sensitive completion.
# CASE_SENSITIVE="true"

# Uncomment the following line to use hyphen-insensitive completion. Case
# sensitive completion must be off. _ and - will be interchangeable.
# HYPHEN_INSENSITIVE="true"

# Uncomment the following line to disable bi-weekly auto-update checks.
# DISABLE_AUTO_UPDATE="true"

# Uncomment the following line to change how often to auto-update (in days).
# export UPDATE_ZSH_DAYS=13

# Uncomment the following line to disable colors in ls.
# DISABLE_LS_COLORS="true"

# Uncomment the following line to disable auto-setting terminal title.
# DISABLE_AUTO_TITLE="true"

# Uncomment the following line to enable command auto-correction.
# ENABLE_CORRECTION="true"

# Uncomment the following line to display red dots whilst waiting for completion.
# COMPLETION_WAITING_DOTS="true"

# Uncomment the following line if you want to disable marking untracked files
# under VCS as dirty. This makes repository status check for large repositories
# much, much faster.
# DISABLE_UNTRACKED_FILES_DIRTY="true"

# Uncomment the following line if you want to change the command execution time
# stamp shown in the history command output.
# The optional three formats: "mm/dd/yyyy"|"dd.mm.yyyy"|"yyyy-mm-dd"
# HIST_STAMPS="mm/dd/yyyy"

# Would you like to use another custom folder than $ZSH/custom?
# ZSH_CUSTOM=/path/to/new-custom-folder

# Which plugins would you like to load? (plugins can be found in ~/.oh-my-zsh/plugins/*)
# Custom plugins may be added to ~/.oh-my-zsh/custom/plugins/
# Example format: plugins=(rails git textmate ruby lighthouse)
# Add wisely, as too many plugins slow down shell startup.
plugins=(
  git
)

source $ZSH/oh-my-zsh.sh

# User configuration

# export MANPATH="/usr/local/man:$MANPATH"

# You may need to manually set your language environment
# export LANG=en_US.UTF-8

# Preferred editor for local and remote sessions
# if [[ -n $SSH_CONNECTION ]]; then
#   export EDITOR='vim'
# else
#   export EDITOR='mvim'
# fi

# Compilation flags
# export ARCHFLAGS="-arch x86_64"

# ssh
# export SSH_KEY_PATH="~/.ssh/rsa_id"

# Set personal aliases, overriding those provided by oh-my-zsh libs,
# plugins, and themes. Aliases can be placed here, though oh-my-zsh
# users are encouraged to define aliases within the ZSH_CUSTOM folder.
# For a full list of active aliases, run `alias`.
#
# Example aliases
# alias zshconfig="mate ~/.zshrc"
# alias ohmyzsh="mate ~/.oh-my-zsh"


# function
## mount with parameter e.g --> mntparam tuan@192.168.0.5 -p22
mntparam() { sudo sshfs "$1:/" /mnt/mntparam -C -o allow_other,IdentityFile=/home/tj/.ssh/id_rsa "$2" ;}
## enable disable touchpad
alias touchon='synclient TouchpadOff=0'
alias touchoff='synclient TouchpadOff=1'

# workspace
alias source-terminal='tmux source-file ~/.tmux.conf && source ~/.zshrc && source ~/.zshenv && source ~/.config/nvim/init.vim && source ~/.vimrc && source ~/.bashrc'
alias zshrc='nvim ~/git/terminal-config/zsh/zshrc'
alias init.vim='nvim  ~/git/terminal-config/vim/init.vim'
alias rn='source ~/project/reactnative/bin/activate'


#source /opt/ros/kinetic/setup.zsh
#source ~/dev_ws/devel/setup.zsh
#export PYTHONPATH=/opt/ros/kinetic/lib/python2.7/dist-packages
#
#export LD_LIBRARY_PATH=/usr/local/cuda/lib64:$LD_LIBRARY_PATH
#export PATH=/usr/local/cuda/bin:$PATH
#export PYTHONPATH=/usr/local/cuda/lib64:$PYTHONPATH
#
#
#alias cuda8='sudo ln -sfn /usr/local/cuda-8.0 /usr/local/cuda'
#alias cuda9='sudo ln -sfn /usr/local/cuda-9.0 /usr/local/cuda'


#alias tensorflow='source ~/tensorflow/bin/activate'
#tensorflow
#export PYTHONPATH=$PYTHONPATH:/home/tj/tensorflow/models
#export PYTHONPATH=$PYTHONPATH:/home/tj/tensorflow/models/slim


#export ANDROID_HOME=~/Android/Sdk
#export PATH=${PATH}:${ANDROID_HOME}/tools
#export PATH=${PATH}:${ANDROID_HOME}/platform-tools
#
#alias avd='cd ~/Android/Sdk/tools/ && emulator @testAVD'
#alias rel='adb shell input keyevent 82'
#alias t='adb shell input keyboard text'


## web scraping
export PATH=~/Downloads/geckodriver:$PATH
#alias npm run android='sudo sysctl -w fs.inotify.max_user_instances=1024 && sudo sysctl -w fs.inotify.max_user_watches=1228'

alias eclipse='PYTHONPATH=$PYTHONPATH:/usr/local/cuda-8.0/lib64 && cd /opt/eclipse_neon/ && ./eclipse'

# Database and Webserver
## webserver
alias apachestart='sudo systemctl start  apache2.service'
alias apachestop='sudo systemctl stop apache2.service'
## database
alias mongodbstart='sudo mongod --dbpath /var/lib/mongodb'
alias postgresqlstart='sudo service postgresql start'
alias postgresqlstop='sudo service postgresql stop'


# Python
alias prettyjson='python -m json.tool'


